GET http://localhost:4100/orders
Authorization: Bearer eyJhbGciOiJFUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjYyMjM4MTI0LCJleHAiOjE2NjI0MTA5MjR9.saWNuv4j3WiptnDMA-VuJ8829Jox0oCLAPzOsk-MGCbt0FW7deN84TXbf1rpOHBsmPW2VoJ1cWBw1tcTLXAFwQ

### GET ONE ORDER

GET http://localhost:4100/orders/13
Authorization: Bearer eyJhbGciOiJFUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjYyMjM4MTI0LCJleHAiOjE2NjI0MTA5MjR9.saWNuv4j3WiptnDMA-VuJ8829Jox0oCLAPzOsk-MGCbt0FW7deN84TXbf1rpOHBsmPW2VoJ1cWBw1tcTLXAFwQ

### PLACE NEW ORDER
POST http://localhost:4100/orders
Authorization: Bearer sample-t0k3n
Content-Type: application/json

{
  "restaurantId": 2,
  "productsIds": [5],
  "address": "My HOME 455"
}

### Unauthorized order
POST http://localhost:4100/orders
